#!/bin/sh

n="$1"
history=./n_history
case "$n" in
[1-9])
	echo "history "$n" selected"
	n="$(tail -n+"$n" "$history" | head -n1)"
	;;
esac

if [ -z "$n" ]; then
	echo 'invalid number' >&2
	exit 1
fi

t="$(mktemp)"

echo "problem "$n" selected"

# Directory existence check
if [ -d "$n" ]; then
	echo "Directory $n already exists."
	while true; do
		read -p "Do you want to flush it? (y/n): " yn
		case $yn in
		[Yy]*)
			rm -rf "$n"
			mkdir "$n"
			break
			;;
		[Nn]*)
			echo "Exiting the program."
			exit
			;;
		*) ;;
		esac
	done
else
	mkdir "$n"
fi

(
	echo "$n"
	if [ -f "$history" ]; then
		grep -v '^'"$n"'$' "$history" | head -n8
	fi
) >"$t"
mv "$t" "$history"

cd "$n"

# Makefile creation
cat <<EOF >Makefile
n = $n
include ../mk
EOF

# Making files
touch input.txt output.txt
cp ../main.cpp ./"$n".cpp

# Read problem information
python3 ../.read.py "$n"

# Open file in editor
nvim "$n".cpp
